_description: |
  A simple subheader component.

type:
  _label: Subheader type
  _has:
    input: radio
    options:
      -
        name: 'small (h4)'
        value: 'small'
      -
        name: 'medium (h3)'
        value: 'medium'
      -
        name: 'large (h2)'
        value: 'large'
text:
  _label: Subheader Text
  _has:
    input: text
link:
  _label: Subheader Link
  _has:
    input: text

_groups:
  subheader:
    fields:
      - text
      - type
      - link
    _placeholder:
      text: Subheader Text
      height: 20px
      ifEmpty: text
