_description: |
  A simple subheader component.

type:
  _label: Type
  _has:
    input: radio
    options:
      - name: "small (h4)"
        value: "small"
      - name: "medium (h3)"
        value: "medium"
      - name: "large (h2)"
        value: "large"
text:
  _label: Subheader Text
  _has:
    input: text
subheaderid:
  _label: Hash (Subheader text if is empty)
  _has:
    input: text

_groups:
  subheader:
    fields:
      - text
      - type
      - subheaderid
    _placeholder:
      text: Subheader Text
      height: 20px
      ifEmpty: text
