_description: |
  A simple subheader component.

# text:
#   _label: Subheader Text
#   _placeholder:
#     height: 20px
#     text: Subheader Text
#   _has:
#     input: inline

type:
  _label: Subheader type
  _has:
    input: radio
    options:
      -
        name: 'small (h4)'
        value: 'small'
      -
        name: 'medium (h3)'
        value: 'madium'
      -
        name: 'large (h2)'
        value: 'large 2'
text:
  _label: Subheader Text
  _has:
    input: text

_groups:
  subheader:
    fields:
      - text
      - type
    _placeholder:
      text: Subheader Text
      height: 20px
      ifEmpty: text
