_description: |
  This is the site header at the top of every page. It displays the site logo, navigational links, account button, and search button.
_confirmRemoval: true

_groups:
  settings:
    fields:
      - mobileCTA
      - mobileCTALink
