version: '3'
services:

  clay:
    build: .
    command: ["npm", "run", "start:dev"]
    expose:
      - 3001
    links:
      - elasticsearch
      - postgres
      - nginx
      - redis
    volumes:
      - ./app/.env:/usr/local/src/.env
      - ./app/app.js:/usr/local/src/app.js
      - ./app/claycli.config.js:/usr/local/src/claycli.config.js
      - ./app/components/:/usr/local/src/components/
      - ./app/layouts/:/usr/local/src/layouts/
      - ./app/nodemon.json:/usr/local/src/nodemon.json
      - ./app/package.json:/usr/local/src/package.json
      - ./app/services/:/usr/local/src/services/
      - ./app/sites/:/usr/local/src/sites/
      - ./app/styleguides/:/usr/local/src/styleguides/

  ################################################
  ## Local Sites Setup:                         ##
  ## Nginx, Elastic Search, Redis               ##
  ################################################
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/configs/:/etc/nginx/conf.d/

  # Event Bus, Postgres Cache and Session Store
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis:/data

  # You know, for search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
    command: ["elasticsearch", "-Elogger.level=ERROR"]
    environment:
      - cluster.routing.allocation.disk.threshold_enabled="false"
      - cluster.routing.allocation.disk.watermark.flood_stage=10mb
      - cluster.routing.allocation.disk.watermark.high=200mb
      - cluster.routing.allocation.disk.watermark.low=50mb
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch:/usr/share/elasticsearch/data

  # Primary data store
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  elasticsearch:
  postgres:
  redis:
